### ISSUE TITLE
nginx won't start

### ISSUE THREAD

**Issue by zhex900** [galexrt/docker-nginx-php-fpm-pagespeed#1]
[root@f83dc92cfe9a /]# /usr/local/nginx/sbin/nginx
nginx: [crit] pread() "/configs" failed (21: Is a directory)

**Comment by galexrt** [comment]
I think you need to change:
https://github.com/galexrt/docker-nginx-php-fpm-pagespeed/blob/master/nginx.conf#L20
to something like:
```
include /configs/*;
```
Could you give that a try and let me know if that fixed the issue?

**Comment by galexrt** [comment]
Closing as not reproducible and no response from issue author.
